DEBUG = True

CAMERA_ENABLED = True
I2C_ENABLED = True
DISTANCE_SENSOR_ENABLED = True

FEED_TIMEOUT = 18000
FEED_URL = "http://10.0.0.100:9090/feed"

SERIAL_DEVICE = '/dev/ttyACM0'

DISTANCE_TRIG_PIN = 23
DISTANCE_ECHO_PIN = 24
