DEBUG = True

CAMERA_ENABLED = True
SERIAL_ENABLED = False
DISTANCE_SENSOR_ENABLED = False

FEED_TIMEOUT = 18000
FEED_URL = "http://10.0.0.100:9090/feed"

SERIAL_DEVICE = '/dev/ttyACM0'

DISTANCE_TRIG_PIN = 23
DISTANCE_ECHO_PIN = 24
